### ISSUE TITLE
Add TravelGroup

### ISSUE THREAD

**Issue by ZeshanShahid79** [ZeshanShahid79/Capstone-expensetracker#14]
## Value Preposition

**As a User** 
**I need** to open/add a new group
**to be able to** have different travel groups with different companions

## Description

Multiple Lists of travelers displayed on the app

## Acceptance Criteria

- [ ] List of Group should be new class wit Travelers

## Tasks

(for developers team)

- [x] create branch add TravelerGroup
- [x] add get method  
- [x] unit and integration test 
- [x] implement TravelGroup list in frontend  (display lists)
