### ISSUE TITLE
update traveler group

### ISSUE THREAD

**Issue by ZeshanShahid79** [ZeshanShahid79/Capstone-expensetracker#15]
## Value Preposition

**As a User** 
**I need** to update my Group 
**to be able to** modify or rename the travel companions(list)

## Description

add a update button to update companion groups

## Acceptance Criteria

- [ ] update button should be on every traveler group

## Tasks

(for developers team)

- [ ] create branch update traveler group 
- [ ] unit and integration test 
- [ ] implement update button in frontend
