### ISSUE TITLE
delete traveler group

### ISSUE THREAD

**Issue by ZeshanShahid79** [ZeshanShahid79/Capstone-expensetracker#16]
## Value Preposition

**As a User** 
**I need** to delete a traveler group
**to be able to** remove a traveler group from the list 

## Description

Delete Button to remove a traveler group

## Acceptance Criteria

- [ ] delete button should be on traveler group (card?)
- [ ] additional delete was successful message 

## Tasks

(for developers team)

- [ ] create branch delete traveler group button 
- [ ] unit and integration test 
- [ ] additional delete message
- [ ] add delete button in frontend
