### ISSUE TITLE
get traveler groups

### ISSUE THREAD

**Issue by ZeshanShahid79** [ZeshanShahid79/Capstone-expensetracker#17]
## Value Preposition

**As a User** 
**I need** see all my travel groups 
**to be able to** get a overview of the travel groups

## Description

List of traveler groups displayed on the app 

## Acceptance Criteria

- [x] List of traveler group should be Type List<TravelerGroup>

## Tasks

(for developers team)

- [x] create branch traveler group List 
- [x] build model - repo, service and controller 
- [x] unit and integration test 
- [x] implement traveler group list in frontend  (display list)
