### ISSUE TITLE
Add conviatores to List 

### ISSUE THREAD

**Issue by ZeshanShahid79** [ZeshanShahid79/Capstone-expensetracker#2]
## Value Preposition

**As a User** 
**I need** to add my travel companions to a list 
**to be able to** get a overview of the travel group 

## Description

List of conviatores diplayed on the app 

## Acceptance Criteria

- [x] List of Conviators should be Type List<String>

## Tasks

(for developers team)

- [x] create branch conviatores List 
- [x] build model - repo, service and controller 
- [x] unit and integration test 
- [x] implement conviators list in frontend  (display list)
