### ISSUE TITLE
add_bill_to_traveler group 

### ISSUE THREAD

**Issue by ZeshanShahid79** [ZeshanShahid79/Capstone-expensetracker#24]
## Value Preposition

**As a User** 
**I need** to have a Bill in my Group 
**to be able to** split up a bill 

## Description

add a bill(amount) to the group

## Tasks

(for developers team)

- [ ] create branch add_bill_to_traveler group 
- [ ] unit and integration test 
- [ ] display bill in frontend
