### ISSUE TITLE
add user button 

### ISSUE THREAD

**Issue by ZeshanShahid79** [ZeshanShahid79/Capstone-expensetracker#3]
## Value Preposition

**As a User** 
**I need** a add "companion" button 
**to be able to** add more travelers to the list 

## Description

Implement Add Button so a new "traveler" can be diplayed in the list 

## Acceptance Criteria

- [ ] new traveler should be Type "user"
- [ ] add button in frontend

## Tasks

(for developers team)

- [ ] create branch add user button 
- [ ] build add method in controller --> service 
- [ ] integration and unit test 
- [ ] implement add button in frontend
