### ISSUE TITLE
update traveler button 

### ISSUE THREAD

**Issue by ZeshanShahid79** [ZeshanShahid79/Capstone-expensetracker#4]
## Value Preposition

**As a User** 
**I need** to update my list 
**to be able to** modify or rename the travel companions(list)

## Description

add a update button to uodate companions

## Acceptance Criteria

- [x] update button should be on every traveler

## Tasks

(for developers team)

- [x] create branch update "traveler" button
- [x] unit and integretaion test 
- [x] implement update button in frontend
