### ISSUE TITLE
delete traveler from list

### ISSUE THREAD

**Issue by ZeshanShahid79** [ZeshanShahid79/Capstone-expensetracker#5]
## Value Preposition

**As a User** 
**I need** to delete a traveler
**to be able to** remove a traveler from the list 

## Description

Delete Button to remove a traveler 

## Acceptance Criteria

- [x] delete button should be on traveler (card?)
- [x] additional delete was successful message 

## Tasks

(for developers team)

- [x] create branch delete traveler button 
- [x] unit and integration test 
- [x] additional delete message
- [x] add delete button in frontend
